# Generated by Django 2.2.6 on 2019-10-15 20:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='contenu',
            field=tinymce.models.HTMLField(default=1, verbose_name='contenu'),
            preserve_default=False,
        ),
    ]
