# Generated by Django 2.2.6 on 2019-10-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191016_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newvideo',
            options={'verbose_name': 'NewVideo', 'verbose_name_plural': 'NewVideo'},
        ),
    ]
