# Generated by Django 2.2.6 on 2019-10-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_commentaire_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaire_article', to='blog.New'),
        ),
    ]
