# Generated by Django 2.2.6 on 2019-10-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191016_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newimage',
            old_name='article',
            new_name='article_image',
        ),
        migrations.RenameField(
            model_name='newvideo',
            old_name='article',
            new_name='article_video',
        ),
    ]
