# Generated by Django 2.2.6 on 2019-10-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_commentaire_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentaire_article', to='blog.New'),
            preserve_default=False,
        ),
    ]
