# Generated by Django 2.2.6 on 2019-10-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_commentaire_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecrit_par', to='blog.Auteur'),
        ),
        migrations.AlterField(
            model_name='new',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_article', to='blog.Categorie'),
        ),
        migrations.AlterField(
            model_name='newimage',
            name='article_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_image', to='blog.New'),
        ),
        migrations.AlterField(
            model_name='newvideo',
            name='article_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_article', to='blog.New'),
        ),
    ]
