# Generated by Django 2.2.6 on 2019-10-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image_preview', models.ImageField(upload_to='images/construction/previews/')),
                ('preview_text', models.TextField()),
                ('adresse', models.CharField(max_length=255)),
                ('prix', models.PositiveIntegerField()),
                ('taille_lot', models.PositiveIntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('est_termine', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allentour', models.ImageField(upload_to='images/construction/localisation')),
                ('interieur', models.ImageField(upload_to='images/construction/localisation')),
                ('piscine', models.ImageField(upload_to='images/construction/localisation')),
                ('vue', models.ImageField(upload_to='images/construction/localisation')),
                ('video_allentour', models.URLField()),
                ('video_interieur', models.URLField()),
                ('video_oiscine', models.URLField()),
                ('video_vue', models.URLField()),
                ('interieur_description', models.TextField()),
                ('environnement_description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
            },
        ),
        migrations.CreateModel(
            name='TypeDeMaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TypeDeMaison',
                'verbose_name_plural': 'TypeDeMaisons',
            },
        ),
        migrations.CreateModel(
            name='Image_interieur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/construction/commodite/')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_image', to='construction.House')),
            ],
            options={
                'verbose_name': 'Commodite',
                'verbose_name_plural': 'Commodites',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='type_maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_de_maison', to='construction.TypeDeMaison'),
        ),
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/construction/commodite/')),
                ('icone_commodite', models.CharField(max_length=70)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_commodite', to='construction.House')),
            ],
            options={
                'verbose_name': 'Commodite',
                'verbose_name_plural': 'Commodites',
            },
        ),
    ]
