# Generated by Django 2.2.6 on 2019-10-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_house_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image_fascade',
            field=models.ImageField(default=1, upload_to='images/construction/fascade/'),
            preserve_default=False,
        ),
    ]
