# Generated by Django 2.2.6 on 2019-10-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_membre_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='bureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='config.Bureau'),
        ),
    ]
