# Generated by Django 2.2.6 on 2019-10-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icone_classe',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
