# Generated by Django 2.2.6 on 2019-10-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20191016_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='identite',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
