# Generated by Django 2.2.6 on 2019-10-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_identite_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerslide',
            name='sous_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='headerslide',
            name='sous_titre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
