# Generated by Django 2.2.6 on 2019-10-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_membre_avatar'),
        ('blog', '0002_new_contenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='prenoms',
        ),
        migrations.AddField(
            model_name='auteur',
            name='membre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='team.Membre'),
            preserve_default=False,
        ),
    ]
