# Generated by Django 2.2.6 on 2019-10-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191016_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.New', verbose_name='article_image'),
        ),
    ]
