# Generated by Django 2.2.6 on 2019-10-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191016_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Auteur', verbose_name='ecrit_par'),
        ),
    ]
