# Generated by Django 2.2.6 on 2019-10-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191016_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='sulg',
            new_name='slug',
        ),
    ]
