# Generated by Django 2.2.6 on 2019-10-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='avatar',
            field=models.ImageField(default=1, upload_to='images/about/team/'),
            preserve_default=False,
        ),
    ]
