# Generated by Django 2.2.6 on 2019-10-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20191016_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apropos',
            name='experience',
        ),
        migrations.AddField(
            model_name='apropos',
            name='annee_creation',
            field=models.DateField(null=True),
        ),
    ]
