# Generated by Django 2.2.6 on 2019-10-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_sociallink_icone_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpage',
            name='compagnie_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='information_legal',
            field=models.BooleanField(default=False),
        ),
    ]
