# Generated by Django 2.2.6 on 2019-10-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20191016_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherpage',
            name='compagnie_page',
        ),
        migrations.RemoveField(
            model_name='otherpage',
            name='information_legal',
        ),
    ]
