# Generated by Django 2.2.6 on 2019-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20191016_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='identite',
            name='footer_logo',
            field=models.ImageField(default=1, upload_to='images/config/'),
            preserve_default=False,
        ),
    ]
