# Generated by Django 2.2.6 on 2019-10-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_identite_footer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identite',
            name='maps_link',
            field=models.TextField(),
        ),
    ]
