# Generated by Django 2.2.6 on 2019-10-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_interieur',
            options={'verbose_name': 'Image_interieur', 'verbose_name_plural': 'Image_interieur'},
        ),
        migrations.RemoveField(
            model_name='commodite',
            name='image',
        ),
    ]
